name: Retrain Model

on:
  push:
    paths:
      - "Data/data_latih_baru.csv"

jobs:
  retrain:
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'Automated update')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Combine datasets and retrain model
      env:
        GROG_API_KEY: ${{ secrets.GROG_API_KEY }}
      run: python retrain_model.py

    - name: Commit and push changes
      run: |
        git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
        git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
        git add Data/data_latih_lama.csv text_clf_lsvc_baru.joblib
        git commit -m "Automated update $(date -u +'%Y-%m-%d %H:%M:%S' --date='+7 hours')"
        git push
